language: cpp

dist: trusty
sudo: required

before_install:
  - sudo apt-get install libssl-dev libgmp-dev build_essential cmake -y
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_relic.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug . && make 
  - echo "Testing Basic Primitives"
  - ./bin/prp
  - ./bin/prg
  - ./bin/com
  - ./bin/hash
  - ./bin/garble 1 12345 & ./bin/garble 2 12345
  - ./bin/netio 1 12345 & ./bin/netio 2 12345
  - echo "Testing Circuits"
  - ./bin/bit
  - ./bin/int
  - ./bin/float