language: cpp


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Release

   - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install libssl-dev libgmp-dev build-essential cmake git -y;
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_relic.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=$TYPE . && make
  - echo "Testing Basic Primitives"
  - ./bin/prp
  - ./bin/prg
  - ./bin/com
  - ./bin/hash
  - ./bin/garble 1 12345 & ./bin/garble 2 12345
  - ./bin/netio 1 12345 & ./bin/netio 2 12345
  - echo "Testing Circuits"
  - ./bin/bit
  - ./bin/int
  - ./bin/float