language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons: TYPE=Debug

    - os: linux
      dist: bionic
      sudo: required
      addons: TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Debug
      
before_install:
  - eval "${MATRIX_EVAL}"
  - git clone -brelease-2 https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_packages.sh
  - sudo apt-get install g++-8 gcc-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
  - g++ --version


script:
  - while sleep 400; do echo "=====[ $SECONDS seconds ]====="; done &
  - cmake -DCMAKE_BUILD_TYPE=$TYPE -DENABLE_FLOAT=On .
  - make 
  - echo "Testing Basic Primitives"
  - ./bin/prp
  - ./bin/prg
  - ./bin/mitccrh
  - ./run ./bin/garble
  - ./run ./bin/netio
  - ./bin/bit
  - ./bin/int
  - ./bin/float
  - ./bin/ecc
  - ./bin/f2k
