language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: xenial
      sudo: required
      env: TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Debug
      
before_install:
  - eval "${MATRIX_EVAL}"
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_packages.sh

script:
  - while sleep 400; do echo "=====[ $SECONDS seconds ]====="; done &
  - cmake -DCMAKE_BUILD_TYPE=$TYPE .
  - make 
  - echo "Testing Basic Primitives"
  - ./bin/prp
  - ./bin/prg
  - ./bin/mitccrh
  - ./run ./bin/garble
  - ./run ./bin/netio
  - ./bin/bit
  - ./bin/int
  - ./bin/float32
  - ./bin/ecc
  - ./bin/f2k
