language: cpp

before_install:
   sudo apt-get install -y software-properties-common
   sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
   sudo apt-get update
   sudo apt-get install -y cmake build-essential libssl-dev libgmp-dev python

matrix:
   include:
      - os: linux
   addons:
      apt:
         sources:
            - ubuntu-toolchain-r-test
         packages:
            - g++-4.9
   env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
   - eval "${MATRIX_EVAL}"

script:
   cmake . && make